package com.authcore.config;

import com.authcore.apikey.ApiKeyStore;
import com.authcore.user.AuthCoreUser;
import com.authcore.user.UserRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.oauth2.core.AuthorizationGrantType;
import org.springframework.security.oauth2.core.ClientAuthenticationMethod;
import org.springframework.security.oauth2.core.oidc.OidcScopes;
import org.springframework.security.oauth2.server.authorization.client.RegisteredClient;
import org.springframework.security.oauth2.server.authorization.client.RegisteredClientRepository;
import org.springframework.security.oauth2.server.authorization.settings.ClientSettings;
import org.springframework.security.oauth2.server.authorization.settings.TokenSettings;
import org.springframework.stereotype.Component;

import java.time.Duration;
import java.time.Instant;
import java.util.Set;
import java.util.UUID;

@Component
public class DataSeeder implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(DataSeeder.class);

    static final String DEMO_API_KEY_NAME = "demo-reporting-job";
    static final String DEMO_API_KEY = "ak_demo_reporting_job_local_only_0000000000";

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final RegisteredClientRepository registeredClientRepository;
    private final ApiKeyStore apiKeyStore;

    public DataSeeder(UserRepository userRepository,
                      PasswordEncoder passwordEncoder,
                      RegisteredClientRepository registeredClientRepository,
                      ApiKeyStore apiKeyStore) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.registeredClientRepository = registeredClientRepository;
        this.apiKeyStore = apiKeyStore;
    }

    @Override
    public void run(ApplicationArguments args) {
        seedUser();
        upsert(confidentialClient());
        upsert(publicSpaClient());
        upsert(machineClient());
        seedApiKey();
    }

    /**
     * Machine-to-machine client: no user involved, so no authorization code, no consent,
     * and no refresh token (it can just ask for another token with its own credentials).
     */
    private RegisteredClient machineClient() {
        return RegisteredClient.withId(UUID.randomUUID().toString())
                .clientId("authcore-machine")
                .clientSecret(passwordEncoder.encode("machine-secret"))
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
                .scope("payments:read")
                .scope("payments:write")
                .tokenSettings(TokenSettings.builder()
                        .accessTokenTimeToLive(Duration.ofMinutes(10))
                        .build())
                .build();
    }

    /**
     * Demo key with a fixed value so the flow is reproducible without a provisioning API.
     * Real keys are generated by {@link ApiKeyStore#generateKey()} and shown once at
     * creation — this seeded one exists only for local demos.
     */
    private void seedApiKey() {
        if (apiKeyStore.existsByName(DEMO_API_KEY_NAME)) return;

        apiKeyStore.save(
                DEMO_API_KEY_NAME,
                DEMO_API_KEY,
                Set.of("payments:read"),
                Instant.now().plus(Duration.ofDays(365)));

        log.warn("Seeded demo API key '{}' with scope payments:read. Local development only.",
                DEMO_API_KEY_NAME);
    }

    private void seedUser() {
        if (userRepository.findByUsername("ezzat").isPresent()) return;

        AuthCoreUser user = new AuthCoreUser();
        user.setUsername("ezzat");
        user.setPasswordHash(passwordEncoder.encode("password"));
        user.getAuthorities().add("ROLE_USER");
        userRepository.save(user);
    }

    /** Server-side client: authenticates with a secret, so PKCE stays optional. */
    private RegisteredClient confidentialClient() {
        return RegisteredClient.withId(UUID.randomUUID().toString())
                .clientId("authcore-client")
                .clientSecret(passwordEncoder.encode("secret"))
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
                .redirectUri("http://127.0.0.1:8080/authorized")
                .scope(OidcScopes.OPENID)
                .scope(OidcScopes.PROFILE)
                .scope("payments:read")
                .scope("payments:write")
                .clientSettings(ClientSettings.builder()
                        .requireAuthorizationConsent(true)
                        .build())
                .tokenSettings(rotatingTokens())
                .build();
    }

    /**
     * Browser/mobile client: ships to the user's device, so it cannot hold a secret.
     * PKCE is mandatory here — it is the only thing binding the authorization code
     * to the client that requested it.
     */
    private RegisteredClient publicSpaClient() {
        return RegisteredClient.withId(UUID.randomUUID().toString())
                .clientId("authcore-spa")
                .clientAuthenticationMethod(ClientAuthenticationMethod.NONE)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
                .redirectUri("http://127.0.0.1:8080/authorized")
                .scope(OidcScopes.OPENID)
                .scope(OidcScopes.PROFILE)
                .scope("payments:read")
                .clientSettings(ClientSettings.builder()
                        .requireProofKey(true)
                        .requireAuthorizationConsent(true)
                        .build())
                .tokenSettings(rotatingTokens())
                .build();
    }

    /** Rotation is what gives reuse detection something to detect. */
    private TokenSettings rotatingTokens() {
        return TokenSettings.builder()
                .reuseRefreshTokens(false)
                .accessTokenTimeToLive(Duration.ofMinutes(5))
                .refreshTokenTimeToLive(Duration.ofDays(7))
                .build();
    }

    /** Re-seeds on every boot so settings changes take effect without a manual DB wipe. */
    private void upsert(RegisteredClient client) {
        RegisteredClient existing = registeredClientRepository.findByClientId(client.getClientId());
        if (existing != null) {
            client = RegisteredClient.from(client).id(existing.getId()).build();
        }
        registeredClientRepository.save(client);
    }
}
